using System;
using System.Linq;
using VideoOS.Platform;
using VideoOS.Platform.Client;
using VideoOS.Platform.ConfigurationItems;
using VideoOS.Platform.Login;

namespace AddUserSample.Client
{
    /// <summary>
    /// This template code should be replaced with your code.
    /// 
    /// The UserControl to be displayed in a side panel in the Smart Client.<br/>
    /// Generated by a plug-ins SidePanelPlugin.
    /// </summary>
    public partial class AddUserSampleSidePanelUserControl : SidePanelUserControl
    {
        public AddUserSampleSidePanelUserControl()
        {
            InitializeComponent();
        }

        public override void Init()
        {
            QueryRoles();
        }

        private void QueryRoles()
        {
            try
            {
                var roleFolder = new RoleFolder();
                var roles = roleFolder.Roles;

                rolesCombobox.DisplayMember = nameof(Role.DisplayName);
                rolesCombobox.ValueMember = nameof(Role.Path);
                rolesCombobox.DataSource = roles.ToArray();
            }
            catch(ArgumentException ex)
            {
                if (ex.Message.Contains("The server doesn't support the specified path"))
                {
                    printMessage("This plugin only support XPCO 10.1a or newer.");
                }
            }
            catch (Exception ex)
            {
                printMessage(ex.Message);
            }
        }

        private void commitButton_Click(object sender, EventArgs e)
        {
            try
            {
                var rolePath = rolesCombobox.SelectedValue;
                var userName = userNameTextBox.Text;
                var password = Util.ToSecureString(passwordTextBox.Text);

                if (rolePath == null)
                {
                    printMessage("Please select a role");
                    return;
                }
                var folder = new BasicUserFolder();
                var addTask = folder.AddBasicUser(userName, "User created by AddUserWithConfigApi sample", password);
                if (addTask.State != StateEnum.Success)
                {
                    printMessage("Failed to create basic user with error: " + addTask.ErrorText);
                    return;
                }
                var newUser = new BasicUser(EnvironmentManager.Instance.CurrentSite.ServerId, addTask.Path);
                var role = new Role(EnvironmentManager.Instance.CurrentSite.ServerId, rolePath as string);
                var result = role.UserFolder.AddRoleMember(newUser.Sid);
                if (result.State == StateEnum.Success)
                {
                    printMessage(String.Format("User '{0}' is successfully created and added to role '{1}'.", userName, rolesCombobox.Text));
                }
                else
                {
                    printMessage("Operation failed with error: " + result.ErrorText);
                }
            }
            catch (Exception ex)
            {
                printMessage(ex.Message);
            }
        }

        private void printMessage(string message)
        {
            resultTextBox.Text = message;
        }
    }
}
