//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zDACS_UnitTests.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.IWebService")]
    public interface IWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Connect", ReplyAction="http://tempuri.org/IWebService/ConnectResponse")]
        DemoACServerApplication.UserDescriptor Connect(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Connect", ReplyAction="http://tempuri.org/IWebService/ConnectResponse")]
        System.Threading.Tasks.Task<DemoACServerApplication.UserDescriptor> ConnectAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUser", ReplyAction="http://tempuri.org/IWebService/GetUserResponse")]
        DemoACServerApplication.UserDescriptor GetUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUser", ReplyAction="http://tempuri.org/IWebService/GetUserResponse")]
        System.Threading.Tasks.Task<DemoACServerApplication.UserDescriptor> GetUserAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetEventTypes", ReplyAction="http://tempuri.org/IWebService/GetEventTypesResponse")]
        DemoACServerApplication.EventDescriptor[] GetEventTypes(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetEventTypes", ReplyAction="http://tempuri.org/IWebService/GetEventTypesResponse")]
        System.Threading.Tasks.Task<DemoACServerApplication.EventDescriptor[]> GetEventTypesAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetDoorControllers", ReplyAction="http://tempuri.org/IWebService/GetDoorControllersResponse")]
        DemoACServerApplication.DoorControllerDescriptor[] GetDoorControllers(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetDoorControllers", ReplyAction="http://tempuri.org/IWebService/GetDoorControllersResponse")]
        System.Threading.Tasks.Task<DemoACServerApplication.DoorControllerDescriptor[]> GetDoorControllersAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetDoors", ReplyAction="http://tempuri.org/IWebService/GetDoorsResponse")]
        DemoACServerApplication.DoorDescriptor[] GetDoors(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetDoors", ReplyAction="http://tempuri.org/IWebService/GetDoorsResponse")]
        System.Threading.Tasks.Task<DemoACServerApplication.DoorDescriptor[]> GetDoorsAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCredentialHolder", ReplyAction="http://tempuri.org/IWebService/GetCredentialHolderResponse")]
        DemoACServerApplication.CredentialHolderDescriptor GetCredentialHolder(System.Guid credentialHolderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCredentialHolder", ReplyAction="http://tempuri.org/IWebService/GetCredentialHolderResponse")]
        System.Threading.Tasks.Task<DemoACServerApplication.CredentialHolderDescriptor> GetCredentialHolderAsync(System.Guid credentialHolderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/SearchCredentialHolders", ReplyAction="http://tempuri.org/IWebService/SearchCredentialHoldersResponse")]
        DemoACServerApplication.CredentialHolderDescriptor[] SearchCredentialHolders(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/SearchCredentialHolders", ReplyAction="http://tempuri.org/IWebService/SearchCredentialHoldersResponse")]
        System.Threading.Tasks.Task<DemoACServerApplication.CredentialHolderDescriptor[]> SearchCredentialHoldersAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetEvents", ReplyAction="http://tempuri.org/IWebService/GetEventsResponse")]
        DemoACServerApplication.BaseEvent[] GetEvents(string userName, string password, int timeoutMilliSecs, long startSequenceNumber, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetEvents", ReplyAction="http://tempuri.org/IWebService/GetEventsResponse")]
        System.Threading.Tasks.Task<DemoACServerApplication.BaseEvent[]> GetEventsAsync(string userName, string password, int timeoutMilliSecs, long startSequenceNumber, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UnlockDoor", ReplyAction="http://tempuri.org/IWebService/UnlockDoorResponse")]
        bool UnlockDoor(string userName, string password, string vmsUserName, System.Guid doorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UnlockDoor", ReplyAction="http://tempuri.org/IWebService/UnlockDoorResponse")]
        System.Threading.Tasks.Task<bool> UnlockDoorAsync(string userName, string password, string vmsUserName, System.Guid doorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/LockDoor", ReplyAction="http://tempuri.org/IWebService/LockDoorResponse")]
        bool LockDoor(string userName, string password, string vmsUserName, System.Guid doorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/LockDoor", ReplyAction="http://tempuri.org/IWebService/LockDoorResponse")]
        System.Threading.Tasks.Task<bool> LockDoorAsync(string userName, string password, string vmsUserName, System.Guid doorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetDoorStatus", ReplyAction="http://tempuri.org/IWebService/GetDoorStatusResponse")]
        DemoACServerApplication.DoorStatus GetDoorStatus(string userName, string password, System.Guid doorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetDoorStatus", ReplyAction="http://tempuri.org/IWebService/GetDoorStatusResponse")]
        System.Threading.Tasks.Task<DemoACServerApplication.DoorStatus> GetDoorStatusAsync(string userName, string password, System.Guid doorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/CloseApp", ReplyAction="http://tempuri.org/IWebService/CloseAppResponse")]
        void CloseApp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/CloseApp", ReplyAction="http://tempuri.org/IWebService/CloseAppResponse")]
        System.Threading.Tasks.Task CloseAppAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/StartAutomateEvents", ReplyAction="http://tempuri.org/IWebService/StartAutomateEventsResponse")]
        void StartAutomateEvents(int frequency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/StartAutomateEvents", ReplyAction="http://tempuri.org/IWebService/StartAutomateEventsResponse")]
        System.Threading.Tasks.Task StartAutomateEventsAsync(int frequency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/StopAutomateEvents", ReplyAction="http://tempuri.org/IWebService/StopAutomateEventsResponse")]
        void StopAutomateEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/StopAutomateEvents", ReplyAction="http://tempuri.org/IWebService/StopAutomateEventsResponse")]
        System.Threading.Tasks.Task StopAutomateEventsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceChannel : zDACS_UnitTests.WebService.IWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClient : System.ServiceModel.ClientBase<zDACS_UnitTests.WebService.IWebService>, zDACS_UnitTests.WebService.IWebService {
        
        public WebServiceClient() {
        }
        
        public WebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DemoACServerApplication.UserDescriptor Connect(string userName, string password) {
            return base.Channel.Connect(userName, password);
        }
        
        public System.Threading.Tasks.Task<DemoACServerApplication.UserDescriptor> ConnectAsync(string userName, string password) {
            return base.Channel.ConnectAsync(userName, password);
        }
        
        public DemoACServerApplication.UserDescriptor GetUser(string userName) {
            return base.Channel.GetUser(userName);
        }
        
        public System.Threading.Tasks.Task<DemoACServerApplication.UserDescriptor> GetUserAsync(string userName) {
            return base.Channel.GetUserAsync(userName);
        }
        
        public DemoACServerApplication.EventDescriptor[] GetEventTypes(string userName, string password) {
            return base.Channel.GetEventTypes(userName, password);
        }
        
        public System.Threading.Tasks.Task<DemoACServerApplication.EventDescriptor[]> GetEventTypesAsync(string userName, string password) {
            return base.Channel.GetEventTypesAsync(userName, password);
        }
        
        public DemoACServerApplication.DoorControllerDescriptor[] GetDoorControllers(string userName, string password) {
            return base.Channel.GetDoorControllers(userName, password);
        }
        
        public System.Threading.Tasks.Task<DemoACServerApplication.DoorControllerDescriptor[]> GetDoorControllersAsync(string userName, string password) {
            return base.Channel.GetDoorControllersAsync(userName, password);
        }
        
        public DemoACServerApplication.DoorDescriptor[] GetDoors(string userName, string password) {
            return base.Channel.GetDoors(userName, password);
        }
        
        public System.Threading.Tasks.Task<DemoACServerApplication.DoorDescriptor[]> GetDoorsAsync(string userName, string password) {
            return base.Channel.GetDoorsAsync(userName, password);
        }
        
        public DemoACServerApplication.CredentialHolderDescriptor GetCredentialHolder(System.Guid credentialHolderId) {
            return base.Channel.GetCredentialHolder(credentialHolderId);
        }
        
        public System.Threading.Tasks.Task<DemoACServerApplication.CredentialHolderDescriptor> GetCredentialHolderAsync(System.Guid credentialHolderId) {
            return base.Channel.GetCredentialHolderAsync(credentialHolderId);
        }
        
        public DemoACServerApplication.CredentialHolderDescriptor[] SearchCredentialHolders(string searchString) {
            return base.Channel.SearchCredentialHolders(searchString);
        }
        
        public System.Threading.Tasks.Task<DemoACServerApplication.CredentialHolderDescriptor[]> SearchCredentialHoldersAsync(string searchString) {
            return base.Channel.SearchCredentialHoldersAsync(searchString);
        }
        
        public DemoACServerApplication.BaseEvent[] GetEvents(string userName, string password, int timeoutMilliSecs, long startSequenceNumber, int count) {
            return base.Channel.GetEvents(userName, password, timeoutMilliSecs, startSequenceNumber, count);
        }
        
        public System.Threading.Tasks.Task<DemoACServerApplication.BaseEvent[]> GetEventsAsync(string userName, string password, int timeoutMilliSecs, long startSequenceNumber, int count) {
            return base.Channel.GetEventsAsync(userName, password, timeoutMilliSecs, startSequenceNumber, count);
        }
        
        public bool UnlockDoor(string userName, string password, string vmsUserName, System.Guid doorId) {
            return base.Channel.UnlockDoor(userName, password, vmsUserName, doorId);
        }
        
        public System.Threading.Tasks.Task<bool> UnlockDoorAsync(string userName, string password, string vmsUserName, System.Guid doorId) {
            return base.Channel.UnlockDoorAsync(userName, password, vmsUserName, doorId);
        }
        
        public bool LockDoor(string userName, string password, string vmsUserName, System.Guid doorId) {
            return base.Channel.LockDoor(userName, password, vmsUserName, doorId);
        }
        
        public System.Threading.Tasks.Task<bool> LockDoorAsync(string userName, string password, string vmsUserName, System.Guid doorId) {
            return base.Channel.LockDoorAsync(userName, password, vmsUserName, doorId);
        }
        
        public DemoACServerApplication.DoorStatus GetDoorStatus(string userName, string password, System.Guid doorId) {
            return base.Channel.GetDoorStatus(userName, password, doorId);
        }
        
        public System.Threading.Tasks.Task<DemoACServerApplication.DoorStatus> GetDoorStatusAsync(string userName, string password, System.Guid doorId) {
            return base.Channel.GetDoorStatusAsync(userName, password, doorId);
        }
        
        public void CloseApp() {
            base.Channel.CloseApp();
        }
        
        public System.Threading.Tasks.Task CloseAppAsync() {
            return base.Channel.CloseAppAsync();
        }
        
        public void StartAutomateEvents(int frequency) {
            base.Channel.StartAutomateEvents(frequency);
        }
        
        public System.Threading.Tasks.Task StartAutomateEventsAsync(int frequency) {
            return base.Channel.StartAutomateEventsAsync(frequency);
        }
        
        public void StopAutomateEvents() {
            base.Channel.StopAutomateEvents();
        }
        
        public System.Threading.Tasks.Task StopAutomateEventsAsync() {
            return base.Channel.StopAutomateEventsAsync();
        }
    }
}
