using System;
using System.Collections.Generic;
using System.Text;
using VideoOS.Platform;
using VideoOS.Platform.Client;
using VideoOS.Platform.Messaging;

namespace Property.Client
{
    /// <summary>
    /// This template code should be replaced with your code.
    /// 
    /// The UserControl to be displayed in a side panel in the Smart Client.<br/>
    /// Generated by a plug-ins SidePanelPlugin.
    /// </summary>
    public partial class PropertySidePanelUserControl : SidePanelUserControl
    {
        private PropertySidePanelPlugin _sidePanel;

        public PropertySidePanelUserControl(PropertySidePanelPlugin sidePanel)
        {
            _sidePanel = sidePanel;
            InitializeComponent();
            
        }

        public override void Init()
        {
            textBoxPropValue.Text = _sidePanel.MyPropValue;
            textBoxShareGlobal.Text = _sidePanel.MyPropShareGlobal;
            textBoxSharedUser.Text = _sidePanel.MyPropSharePrivate;
            PropertyDefinition.SharedPropertyChanged += PropertyDefinition_SharedPropertyChanged;
        }
        public override void Close()
        {
            PropertyDefinition.SharedPropertyChanged -= PropertyDefinition_SharedPropertyChanged;
            _sidePanel.MyPropValue = textBoxPropValue.Text;
            _sidePanel.MyPropShareGlobal = textBoxShareGlobal.Text;
            _sidePanel.MyPropSharePrivate = textBoxSharedUser.Text;            
        }

        private void PropertyDefinition_SharedPropertyChanged(object sender, System.EventArgs e)
        {
            textBoxShareGlobal.Text = _sidePanel.MyPropShareGlobal;
            textBoxSharedUser.Text = _sidePanel.MyPropSharePrivate;
        }

        private void textBoxShareGlobal_TextChanged(object sender, EventArgs e)
        {
            _sidePanel.MyPropShareGlobal = textBoxShareGlobal.Text;
        }

        private void textBoxSharedUser_TextChanged(object sender, EventArgs e)
        {
            _sidePanel.MyPropSharePrivate = textBoxSharedUser.Text;
        }
    }
}
